#!/usr/bin/env node
/**
 * The correctness gate for the swap math. Offline, no key, no network.
 *
 * This package computes swap output itself instead of depending on
 * `@uniswap/v3-sdk`, because that dependency drags in ~300MB of Solidity build
 * artifacts (hardhat → @nomicfoundation/edr-* prebuilt binaries) onto every
 * `npx` cold start. Rolling your own protocol math is normally a bad trade — so
 * the deal we make here is that it must be provably identical to the SDK, not
 * approximately so.
 *
 * test/fixtures/v3-quote-oracle.json holds real mainnet pool state (USDC/WETH
 * 0.3%, 641 initialised ticks) together with expected outputs GENERATED BY
 * @uniswap/v3-sdk. Regenerate with `node scripts/gen-oracle.mjs` (that script,
 * and only that script, needs the SDK installed).
 *
 * Every case must match to the WEI. "Close" is a failure: rounding direction is
 * exactly where a reimplementation of this math goes wrong, and a quote that is
 * one wei off is a quote that disagrees with the chain.
 *
 * Exit 0 = pass, non-zero = fail.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { swapExactIn, getSqrtRatioAtTick, swapV2ExactIn } from "../dist/v3math.js";

const oracle = JSON.parse(readFileSync(join(process.cwd(), "test/fixtures/v3-quote-oracle.json"), "utf8"));
let failures = 0;
const fail = (m) => { console.error(`  FAIL ${m}`); failures++; };
const ok = (m) => console.log(`  ok   ${m}`);

console.log("TickMath");
// Anchor value from the Uniswap V3 whitepaper / core tests: sqrt(1) in Q64.96.
if (getSqrtRatioAtTick(0) === 79228162514264337593543950336n) ok("tick 0 -> 2^96");
else fail(`tick 0 -> ${getSqrtRatioAtTick(0)}`);
// Monotonicity across a wide span catches a mis-transcribed magic constant,
// which is otherwise invisible until some specific tick range is exercised.
let mono = true, prev = getSqrtRatioAtTick(-887272);
for (let t = -887000; t <= 887000; t += 5000) {
  const v = getSqrtRatioAtTick(t);
  if (v <= prev) { mono = false; break; }
  prev = v;
}
mono ? ok("monotonic across full tick range") : fail("sqrt ratio not monotonic in tick");

console.log("\nV3 swap vs @uniswap/v3-sdk oracle (must be wei-exact)");
const pool = {
  sqrtPriceX96: oracle.pool.sqrtPrice,
  liquidity: oracle.pool.liquidity,
  tick: oracle.pool.tick,
  feePips: oracle.pool.fee,
  ticks: oracle.ticks,
};
for (const c of oracle.cases) {
  if (!c.outRaw) continue; // SDK itself errored on this case; nothing to pin
  const zeroForOne = c.tokenIn === oracle.pool.token0.sym;
  let res;
  try { res = swapExactIn(pool, BigInt(c.amountIn), zeroForOne); }
  catch (e) { fail(`${c.tokenIn} ${c.amountIn} threw: ${e.message}`); continue; }
  const expected = BigInt(c.outRaw);
  if (res.amountOut !== expected) {
    fail(`${c.tokenIn} ${c.amountIn}: expected ${expected}, got ${res.amountOut} (delta ${res.amountOut - expected})`);
  } else if (res.endTick !== c.endTick) {
    fail(`${c.tokenIn} ${c.amountIn}: output exact but endTick ${res.endTick} != ${c.endTick}`);
  } else {
    ok(`${c.tokenIn} ${c.amountIn} -> ${res.amountOut} (endTick ${res.endTick}, crossed ${res.ticksCrossed})`);
  }
}

console.log("\nGuards");
// A trade far larger than the window must SAY so rather than under-quote silently.
const huge = swapExactIn(pool, 10n ** 24n, false);
huge.ranOutOfTicks ? ok("oversized trade reports ranOutOfTicks") : fail("oversized trade did not set ranOutOfTicks");
// Monotonicity: more in, never less out.
let last = -1n, monoOut = true;
for (const amt of [10n ** 15n, 10n ** 17n, 10n ** 18n, 10n ** 19n]) {
  const r = swapExactIn(pool, amt, false);
  if (r.amountOut < last) { monoOut = false; break; }
  last = r.amountOut;
}
monoOut ? ok("output monotonic in input") : fail("output not monotonic in input");

console.log("\nV2 constant product");
// 1000 in against 1e6/1e6 reserves, 0.3% fee: floor(997000*1e6 / (1e6*1000 + 997000))
{
  const got = swapV2ExactIn(1_000_000n, 1_000_000n, 1000n);
  const inWithFee = 1000n * 9970n;
  const want = (inWithFee * 1_000_000n) / (1_000_000n * 10_000n + inWithFee);
  got === want ? ok(`v2 exact-in ${got}`) : fail(`v2 expected ${want}, got ${got}`);
}

console.log(failures === 0 ? "\nquote-math: PASS" : `\nquote-math: ${failures} FAILURE(S)`);
process.exit(failures === 0 ? 0 : 1);
