/**
 * Uniswap V3/V4 concentrated-liquidity swap math — exact, offline, zero-dependency.
 *
 * WHY THIS EXISTS RATHER THAN `@uniswap/v3-sdk`
 * The SDK does this correctly, but pulling it in costs ~300MB of node_modules:
 * `@uniswap/v3-sdk` → `@uniswap/swap-router-contracts` → `hardhat-watcher` →
 * hardhat → `@nomicfoundation/edr-*` prebuilt binaries for every platform
 * (~220MB alone). Those are Solidity build artifacts, not runtime code, but npm
 * installs them anyway because they are declared as production dependencies.
 * This server is launched with `npx`, so that cost is paid on every cold start
 * by every user. The whole implementation below is ~200 lines of BigInt.
 *
 * HOW WE KNOW IT IS RIGHT
 * It is not "believed equivalent" to the SDK — it is *tested* equivalent, to the
 * wei, against outputs generated BY the SDK. See test/fixtures/v3-quote-oracle.json
 * and scripts/gen-oracle.mjs. At the time of writing all 7 oracle cases match
 * exactly in both directions, including trades that cross many initialised ticks.
 * If you change anything here, that test must still pass.
 *
 * This is a faithful port of Uniswap V3 core's TickMath, SqrtPriceMath and
 * SwapMath. Rounding directions are load-bearing: they are what keep the result
 * wei-identical to the protocol rather than merely close.
 */

const Q96 = 1n << 96n;
const MAX_UINT256 = (1n << 256n) - 1n;

export const MIN_TICK = -887272;
export const MAX_TICK = 887272;
export const MIN_SQRT_RATIO = 4295128739n;
export const MAX_SQRT_RATIO = 1461446703485210103287273052203988822378723970342n;

/** Fee tier → tick spacing. V4 pools may use other spacings; read it from the pool. */
export const TICK_SPACINGS: Record<number, number> = { 100: 1, 500: 10, 3000: 60, 10000: 200 };

const MAGIC: ReadonlyArray<readonly [number, bigint]> = [
  [0x2, 0xfff97272373d413259a46990580e213an], [0x4, 0xfff2e50f5f656932ef12357cf3c7fdccn],
  [0x8, 0xffe5caca7e10e4e61c3624eaa0941cd0n], [0x10, 0xffcb9843d60f6159c9db58835c926644n],
  [0x20, 0xff973b41fa98c081472e6896dfb254c0n], [0x40, 0xff2ea16466c96a3843ec78b326b52861n],
  [0x80, 0xfe5dee046a99a2a811c461f1969c3053n], [0x100, 0xfcbe86c7900a88aedcffc83b479aa3a4n],
  [0x200, 0xf987a7253ac413176f2b074cf7815e54n], [0x400, 0xf3392b0822b70005940c7a398e4b70f3n],
  [0x800, 0xe7159475a2c29b7443b29c7fa6e889d9n], [0x1000, 0xd097f3bdfd2022b8845ad8f792aa5825n],
  [0x2000, 0xa9f746462d870fdf8a65dc1f90e061e5n], [0x4000, 0x70d869a156d2a1b890bb3df62baf32f7n],
  [0x8000, 0x31be135f97d08fd981231505542fcfa6n], [0x10000, 0x9aa508b5b7a84e1c677de54f3e99bc9n],
  [0x20000, 0x5d6af8dedb81196699c329225ee604n], [0x40000, 0x2216e584f5fa1ea926041bedfe98n],
  [0x80000, 0x48a170391f7dc42444e8fa2n],
];

/** TickMath.getSqrtRatioAtTick — Q64.96 sqrt price at a tick. */
export function getSqrtRatioAtTick(tick: number): bigint {
  const abs = tick < 0 ? -tick : tick;
  if (abs > MAX_TICK) throw new Error(`tick ${tick} out of range`);
  let ratio = (abs & 0x1) !== 0 ? 0xfffcb933bd6fad37aa2d162d1a594001n : 0x100000000000000000000000000000000n;
  for (const [bit, mul] of MAGIC) if ((abs & bit) !== 0) ratio = (ratio * mul) >> 128n;
  if (tick > 0) ratio = MAX_UINT256 / ratio;
  return (ratio >> 32n) + (ratio % (1n << 32n) === 0n ? 0n : 1n);
}

/** Largest tick whose sqrt ratio is <= sqrtPriceX96. Binary search: TickMath's
 *  bit-twiddling inverse buys nothing here and is far easier to get wrong. */
export function getTickAtSqrtRatio(sqrtPriceX96: bigint): number {
  let lo = MIN_TICK, hi = MAX_TICK;
  while (lo < hi) {
    const mid = Math.ceil((lo + hi) / 2);
    if (getSqrtRatioAtTick(mid) <= sqrtPriceX96) lo = mid; else hi = mid - 1;
  }
  return lo;
}

const divUp = (a: bigint, b: bigint): bigint => a / b + (a % b > 0n ? 1n : 0n);
const mulDivUp = (a: bigint, b: bigint, d: bigint): bigint => divUp(a * b, d);

function amount0Delta(a: bigint, b: bigint, liquidity: bigint, roundUp: boolean): bigint {
  if (a > b) [a, b] = [b, a];
  const n1 = liquidity << 96n, n2 = b - a;
  return roundUp ? divUp(mulDivUp(n1, n2, b), a) : (n1 * n2) / b / a;
}
function amount1Delta(a: bigint, b: bigint, liquidity: bigint, roundUp: boolean): bigint {
  if (a > b) [a, b] = [b, a];
  return roundUp ? mulDivUp(liquidity, b - a, Q96) : (liquidity * (b - a)) / Q96;
}
function nextSqrtFromAmount0RoundingUp(sp: bigint, L: bigint, amt: bigint, add: boolean): bigint {
  if (amt === 0n) return sp;
  const n1 = L << 96n;
  if (add) {
    const product = amt * sp;
    if (product / amt === sp) {
      const denom = n1 + product;
      if (denom >= n1) return mulDivUp(n1, sp, denom);
    }
    return divUp(n1, n1 / sp + amt);
  }
  return mulDivUp(n1, sp, n1 - amt * sp);
}
function nextSqrtFromAmount1RoundingDown(sp: bigint, L: bigint, amt: bigint, add: boolean): bigint {
  return add ? sp + (amt * Q96) / L : sp - mulDivUp(amt, Q96, L);
}
function nextSqrtFromInput(sp: bigint, L: bigint, amountIn: bigint, zeroForOne: boolean): bigint {
  return zeroForOne
    ? nextSqrtFromAmount0RoundingUp(sp, L, amountIn, true)
    : nextSqrtFromAmount1RoundingDown(sp, L, amountIn, true);
}

interface Step { next: bigint; amountIn: bigint; amountOut: bigint; feeAmount: bigint }

/** SwapMath.computeSwapStep, exact-input only (this server never quotes exact-output). */
function computeSwapStep(cur: bigint, target: bigint, L: bigint, remaining: bigint, feePips: number): Step {
  const zeroForOne = cur >= target;
  const remainingLessFee = (remaining * BigInt(1_000_000 - feePips)) / 1_000_000n;
  let amountIn = zeroForOne ? amount0Delta(target, cur, L, true) : amount1Delta(cur, target, L, true);
  const next = remainingLessFee >= amountIn ? target : nextSqrtFromInput(cur, L, remainingLessFee, zeroForOne);
  const reachedTarget = next === target;

  let amountOut: bigint;
  if (zeroForOne) {
    amountIn = reachedTarget ? amountIn : amount0Delta(next, cur, L, true);
    amountOut = amount1Delta(next, cur, L, false);
  } else {
    amountIn = reachedTarget ? amountIn : amount1Delta(cur, next, L, true);
    amountOut = amount0Delta(cur, next, L, false);
  }
  // Partial fill consumes the whole remainder; the fee is what is left over
  // after the input actually swapped. Full fill charges fee on top.
  const feeAmount = !reachedTarget
    ? remaining - amountIn
    : mulDivUp(amountIn, BigInt(feePips), BigInt(1_000_000 - feePips));
  return { next, amountIn, amountOut, feeAmount };
}

export interface TickData { /** tickIdx */ i: number; /** liquidityNet as a decimal string */ net: string }

export interface PoolState {
  sqrtPriceX96: string | bigint;
  liquidity: string | bigint;
  tick: number;
  /** fee in hundredths of a bip: 3000 == 0.30% */
  feePips: number;
  /** initialised ticks; may be a WINDOW around the current tick, not the full range */
  ticks: TickData[];
}

export interface SwapResult {
  amountOut: bigint;
  endSqrtPriceX96: bigint;
  endTick: number;
  endLiquidity: bigint;
  /** true when the swap consumed every tick we hold — the quote is a LOWER BOUND,
   *  not an answer, because liquidity beyond the window was never considered. */
  ranOutOfTicks: boolean;
  ticksCrossed: number;
}

/**
 * Exact-input swap simulation.
 *
 * `zeroForOne` = selling token0 for token1 (price moves down).
 *
 * The tick list is usually a window, so `ranOutOfTicks` matters: a large trade can
 * walk past everything we fetched. Callers MUST surface that rather than present
 * the number as a quote — a confidently wrong price is worse than no price, and it
 * is precisely the failure this package exists to avoid.
 */
export function swapExactIn(pool: PoolState, amountIn: bigint, zeroForOne: boolean): SwapResult {
  let sqrtPrice = BigInt(pool.sqrtPriceX96);
  let liquidity = BigInt(pool.liquidity);
  let tick = Number(pool.tick);
  let remaining = amountIn;
  let amountOut = 0n;
  let ticksCrossed = 0;

  const limit = zeroForOne ? MIN_SQRT_RATIO + 1n : MAX_SQRT_RATIO - 1n;
  const asc = [...pool.ticks].sort((a, b) => a.i - b.i);
  const desc = [...asc].reverse();

  while (remaining > 0n && sqrtPrice !== limit) {
    const nextTick = zeroForOne ? desc.find((x) => x.i < tick) ?? desc.find((x) => x.i === tick)
                                : asc.find((x) => x.i > tick);
    if (!nextTick) {
      return { amountOut, endSqrtPriceX96: sqrtPrice, endTick: tick, endLiquidity: liquidity, ranOutOfTicks: true, ticksCrossed };
    }
    const sqrtAtTick = getSqrtRatioAtTick(nextTick.i);
    const target = zeroForOne ? (sqrtAtTick < limit ? limit : sqrtAtTick)
                              : (sqrtAtTick > limit ? limit : sqrtAtTick);

    const step = computeSwapStep(sqrtPrice, target, liquidity, remaining, pool.feePips);
    sqrtPrice = step.next;
    remaining -= step.amountIn + step.feeAmount;
    amountOut += step.amountOut;

    if (sqrtPrice === sqrtAtTick) {
      let net = BigInt(nextTick.net);
      if (zeroForOne) net = -net;
      liquidity += net;
      tick = zeroForOne ? nextTick.i - 1 : nextTick.i;
      ticksCrossed++;
      if (liquidity <= 0n) {
        // No liquidity left in range within our window — stop rather than divide by zero.
        return { amountOut, endSqrtPriceX96: sqrtPrice, endTick: tick, endLiquidity: liquidity, ranOutOfTicks: true, ticksCrossed };
      }
    } else {
      tick = getTickAtSqrtRatio(sqrtPrice);
    }
  }
  return { amountOut, endSqrtPriceX96: sqrtPrice, endTick: tick, endLiquidity: liquidity, ranOutOfTicks: false, ticksCrossed };
}

/** Constant-product (V2) exact-input, 0.30% fee. Exact, and far simpler than V3. */
export function swapV2ExactIn(reserveIn: bigint, reserveOut: bigint, amountIn: bigint, feeBps = 30n): bigint {
  const inWithFee = amountIn * (10_000n - feeBps);
  return (inWithFee * reserveOut) / (reserveIn * 10_000n + inWithFee);
}

/** Human price of token1 per token0 implied by a sqrt ratio, decimal-adjusted. */
export function priceFromSqrt(sqrtPriceX96: bigint, dec0: number, dec1: number): number {
  const num = Number(sqrtPriceX96) ** 2;
  return (num / Number(Q96) ** 2) * 10 ** (dec0 - dec1);
}
